FROM eclipse-temurin:17-jdk-alpine AS builder
WORKDIR /app
COPY . .
RUN chmod +x gradlew
RUN ./gradlew clean build --no-daemon

# Для запуска тестов
FROM eclipse-temurin:17-jdk-alpine AS test-runner
WORKDIR /app
COPY --from=builder /app .
RUN chmod +x gradlew
CMD ["./gradlew", "test", "--no-daemon"]